### ISSUE TITLE
Python 3.11.4 Error

### ISSUE THREAD

**Issue by Kyusetzu** [sam-roberts/Oura-data-visualiser#3]
Hello hello.

I'd recommend to specify which python version you are using.

Ubuntu 23.04 ships with
```
(venv) root@oura:/home/oura-data-visualiser# python3 --version
Python 3.11.4
```

So I'm getting the following error after following the provided guide:

```
(venv) root@oura:/home/oura-data-visualiser# python3 sleep-data.py
Request failed with status code: 403
Traceback (most recent call last):
  File "/home/oura-data-visualiser/sleep-data.py", line 231, in <module>
    main()
  File "/home/oura-data-visualiser/sleep-data.py", line 210, in main
    sleepData = getSleepData(config, myParams)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oura-data-visualiser/sleep-data.py", line 174, in getSleepData
    sleepData = sleepData.get("data")
                ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
```

So you should either specifiy which python version you are using, or adapt to Python 3.11...

**Comment by sam-roberts** [comment]
Hey @Kyusetzu thanks for reporting this, I will look into it and get back to you. 
Dev was done on Python 3.9.2

**Comment by sam-roberts** [comment]
@Kyusetzu Just double checking you've added your personal token to the config file? It seems like 
`getResponseFromAPI(
`
has not returned anything. The request to the oura api returned a 403 meaning you don't have permission.
Double check the values of:

`sleep_api_url = https://api.ouraring.com/v2/usercollection/daily_sleep`

and

`personal_token = YOUNEEDTOREPLACETHISWITHYOUROWNNUMBER`



Potentially also try running
pip install --upgrade -r requirements.txt

then run again to see if that helps

**Comment by Kyusetzu** [comment]
@sam-roberts I just read up on stuff.
Absolutely not your fault as it seems.
With no membership the api wont let you access the API.

Idk if you can instead create a error message :D

Had to read up on it a bit since I didnt realize why that happens even with all correct data filled in..

**Comment by sam-roberts** [comment]
Thanks for figuring it out, I'll improve the error messaging.
